Original
CelestialAmber/TetrisNESDisasm pull request #6
Opened 2022-01-28 06:09 UTC by fractal161

Been doing a lot of things with the asm lately, and i decided to make some annotations since i'm not familiar with all aspects of nes programming yet. this led to a fair bit of relabeling, where I added some ejona labels and renamed some things on my own too (those should probably be given to taus later). My plan is now to convert all of the LXXX labels into something readable, since I have this vision of the disasm becoming a way to introduce people to romhacking or smth. hopefully you find this interesting :).

(also ignore the makefile i am sorry)

2022-01-28 06:10 UTC, fractal161 commented
ah, also forgot to add but i did make sure i didn't break the checksum so the code should be correct at least

2022-03-10 21:46 UTC, CelestialAmber commented
Sorry for not looking at this earlier. I'll look at it either today or tommorow.

2022-03-19 16:25 UTC, CelestialAmber commented
So first thing, does the makefile not work on Windows as is?

2022-03-19 20:33 UTC, fractal161 commented
Well I'm running Ubuntu so I wouldn't know :P.

2022-03-19 20:39 UTC, CelestialAmber commented
Does it not work on Ubuntu? If so what error does it give?

2022-04-20 23:07 UTC, CelestialAmber requested changes

2022-04-20 23:07 UTC, CelestialAmber commented on audio/music/music1.asm
> +; There are 3 main types of commands, that controller the instrument, duration, and pitch of the note
that controls the instrument

2022-04-20 23:08 UTC, CelestialAmber commented
Sorry for taking so long to look at this. Once you fix the typo and revert your changes on the Makefile I'll merge this.

2022-04-20 23:11 UTC, CelestialAmber commented
Also since I don't have a Linux computer, if you could get the Makefile to also work with Linux while not breaking Mac support with Wine I would really appreciate it. You don't have to though ofc.

2022-04-28 22:31 UTC, fractal161 commented
done.

regarding the makefile, i vaguely recall having some issues with wine in the past, but everything seemed to work just fine now (maybe it was just slow so i changed to local binaries?). i remember that git update-index exists so everything should be fine now.

2022-04-28 23:47 UTC, merged